#!/usr/bin/env bash

# this is just a message to the user
dir=$(pwd)
user=$(whoami)
echo "Hi $user this is a sipmle program i am working on to learn bash have fun :)"
echo ----------------------------------------------------------------------------

# main code
echo if you dont know how to use gish type help well right now you have to type help to get passed this message.
gish-help() {
cat << _EOF_
  gish is a simple program to make things easy and fun for the user
  if you don't know how to use gish all you have to do at the moment is answer the questions 
  and it will run the correct comands you want to run.
_EOF_

}

# help
read h
if [  "$h" == "help" ]; then
        gish-help
fi

echo --------------------------------------------------------------------------
echo hint you can exit the program at any time by pressing control c


# update the system
echo do you want to update?

read up
if [  "$up" == "yes" ]; then
        echo okay updating at $dir
	sleep 2
        sudo apt update
	sudo apt upgrade -yy 
fi


if [  "$up" == "no" ]; then
	echo -----------------
	echo - okay quiting -
	echo -----------------
	sleep 2
        exit
fi
echo --------------------------------
echo --------------------------------
echo --- -system update complete- ---
echo --------------------------------
echo --------------------------------
echo --------------------------------
echo do you want to clean your system?

# clean the system
read clean
if [  "$clean" == "yes" ]; then
	echo okay system clean up commencing at $dir
	sleep 2
        sudo apt-get autoremove -yy
	sudo apt-get autoclean
fi


if [  "$clean" == "no" ]; then
        echo -----------------
        echo - okay quiting -
        echo -----------------
	sleep 2 
        exit
fi

echo -------------------------------
echo -------------------------------
echo - system clean up Comeplete -
echo -------------------------------
echo -------------------------------
echo -------------------------------
echo -------------------------------



# system info
neofetch
#or if you want to use pfetch
#pfetch













